"""Top-50 US by market cap + Top-50 China ADR universe."""

US_TOP50 = [
    ("NVDA", "NVIDIA", "Technology"),
    ("MSFT", "Microsoft", "Technology"),
    ("AAPL", "Apple", "Technology"),
    ("GOOGL", "Alphabet", "Communication Services"),
    ("AMZN", "Amazon", "Consumer Cyclical"),
    ("META", "Meta Platforms", "Communication Services"),
    ("AVGO", "Broadcom", "Technology"),
    ("TSLA", "Tesla", "Consumer Cyclical"),
    ("BRK-B", "Berkshire Hathaway", "Financial Services"),
    ("LLY", "Eli Lilly", "Healthcare"),
    ("JPM", "JPMorgan Chase", "Financial Services"),
    ("WMT", "Walmart", "Consumer Defensive"),
    ("V", "Visa", "Financial Services"),
    ("XOM", "Exxon Mobil", "Energy"),
    ("UNH", "UnitedHealth", "Healthcare"),
    ("MA", "Mastercard", "Financial Services"),
    ("ORCL", "Oracle", "Technology"),
    ("COST", "Costco", "Consumer Defensive"),
    ("PG", "Procter & Gamble", "Consumer Defensive"),
    ("HD", "Home Depot", "Consumer Cyclical"),
    ("JNJ", "Johnson & Johnson", "Healthcare"),
    ("NFLX", "Netflix", "Communication Services"),
    ("BAC", "Bank of America", "Financial Services"),
    ("ABBV", "AbbVie", "Healthcare"),
    ("CRM", "Salesforce", "Technology"),
    ("CVX", "Chevron", "Energy"),
    ("KO", "Coca-Cola", "Consumer Defensive"),
    ("MRK", "Merck", "Healthcare"),
    ("AMD", "AMD", "Technology"),
    ("PEP", "PepsiCo", "Consumer Defensive"),
    ("TMO", "Thermo Fisher", "Healthcare"),
    ("LIN", "Linde", "Basic Materials"),
    ("CSCO", "Cisco", "Technology"),
    ("ADBE", "Adobe", "Technology"),
    ("ACN", "Accenture", "Technology"),
    ("MCD", "McDonald's", "Consumer Cyclical"),
    ("WFC", "Wells Fargo", "Financial Services"),
    ("ABT", "Abbott Labs", "Healthcare"),
    ("GE", "GE Aerospace", "Industrials"),
    ("IBM", "IBM", "Technology"),
    ("CAT", "Caterpillar", "Industrials"),
    ("PM", "Philip Morris", "Consumer Defensive"),
    ("AXP", "American Express", "Financial Services"),
    ("DIS", "Disney", "Communication Services"),
    ("ISRG", "Intuitive Surgical", "Healthcare"),
    ("NOW", "ServiceNow", "Technology"),
    ("GS", "Goldman Sachs", "Financial Services"),
    ("TXN", "Texas Instruments", "Technology"),
    ("VZ", "Verizon", "Communication Services"),
    ("QCOM", "Qualcomm", "Technology"),
]

CHINA_ADR50 = [
    ("BABA", "Alibaba", "Consumer Cyclical"),
    ("PDD", "PDD Holdings", "Consumer Cyclical"),
    ("JD", "JD.com", "Consumer Cyclical"),
    ("BIDU", "Baidu", "Communication Services"),
    ("NTES", "NetEase", "Communication Services"),
    ("TCEHY", "Tencent", "Communication Services"),
    ("NIO", "NIO", "Consumer Cyclical"),
    ("LI", "Li Auto", "Consumer Cyclical"),
    ("XPEV", "XPeng", "Consumer Cyclical"),
    ("BILI", "Bilibili", "Communication Services"),
    ("TME", "Tencent Music", "Communication Services"),
    ("YMM", "Full Truck Alliance", "Industrials"),
    ("TAL", "TAL Education", "Consumer Defensive"),
    ("EDU", "New Oriental", "Consumer Defensive"),
    ("BEKE", "KE Holdings", "Real Estate"),
    ("ZTO", "ZTO Express", "Industrials"),
    ("HTHT", "H World Group", "Consumer Cyclical"),
    ("YY", "JOYY", "Communication Services"),
    ("DQ", "Daqo New Energy", "Technology"),
    ("LU", "Lufax", "Financial Services"),
    ("FUTU", "Futu Holdings", "Financial Services"),
    ("TIGR", "UP Fintech", "Financial Services"),
    ("WB", "Weibo", "Communication Services"),
    ("VIPS", "Vipshop", "Consumer Cyclical"),
    ("ZH", "Zhihu", "Communication Services"),
    ("IQ", "iQIYI", "Communication Services"),
    ("HUYA", "HUYA", "Communication Services"),
    ("DOYU", "DouYu", "Communication Services"),
    ("KC", "Kingsoft Cloud", "Technology"),
    ("GDS", "GDS Holdings", "Technology"),
    ("ATHM", "Autohome", "Communication Services"),
    ("QFIN", "Qifu Technology", "Financial Services"),
    ("YRD", "Yiren Digital", "Financial Services"),
    ("FINV", "FinVolution", "Financial Services"),
    ("NOAH", "Noah Holdings", "Financial Services"),
    ("JFIN", "Jiayin Group", "Financial Services"),
    ("MNSO", "MINISO", "Consumer Cyclical"),
    ("LKNCY", "Luckin Coffee", "Consumer Cyclical"),
    ("GOTU", "Gaotu Techedu", "Consumer Defensive"),
    ("NTCL", "NetClass Technology", "Consumer Defensive"),
    ("RLX", "RLX Technology", "Consumer Defensive"),
    ("CAAS", "China Automotive", "Consumer Cyclical"),
    ("SOHU", "Sohu", "Communication Services"),
    ("SINA", "Sina", "Communication Services"),
    ("NCTY", "The9", "Communication Services"),
    ("CYD", "China Yuchai", "Industrials"),
    ("LX", "LexinFintech", "Financial Services"),
    ("HOLI", "Hollysys", "Technology"),
    ("BZUN", "Baozun", "Consumer Cyclical"),
    ("ZLAB", "Zai Lab", "Healthcare"),
]


def all_tickers():
    us = [(t, n, s, "US") for t, n, s in US_TOP50]
    cn = [(t, n, s, "CN-ADR") for t, n, s in CHINA_ADR50]
    return us + cn
